#!/usr/bin/env node

/**
 * Code Muse Board - Setup Script
 * This script helps you configure the application quickly
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m'
};

// Create readline interface
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Helper function to ask questions
function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, resolve);
  });
}

// Helper function to log with colors
function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

// Main setup function
async function setup() {
  log('\n🚀 Code Muse Board - Setup Wizard', 'cyan');
  log('=====================================\n', 'cyan');

  try {
    // Check if .env already exists
    const envPath = path.join(__dirname, '.env');
    if (fs.existsSync(envPath)) {
      const overwrite = await askQuestion('⚠️  .env file already exists. Overwrite? (y/N): ');
      if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
        log('Setup cancelled.', 'yellow');
        rl.close();
        return;
      }
    }

    log('📝 Let\'s configure your environment...\n', 'blue');

    // OpenAI Configuration
    log('🤖 OpenAI Configuration', 'magenta');
    log('Get your API key from: https://platform.openai.com/api-keys\n', 'yellow');
    
    const openaiKey = await askQuestion('OpenAI API Key (optional, press Enter to skip): ');
    const openaiModel = await askQuestion('OpenAI Model (gpt-3.5-turbo/gpt-4) [gpt-3.5-turbo]: ') || 'gpt-3.5-turbo';
    const maxTokens = await askQuestion('Max tokens for summaries (100-500) [200]: ') || '200';

    // Server Configuration
    log('\n🖥️  Server Configuration', 'magenta');
    const port = await askQuestion('Server port [3001]: ') || '3001';
    const nodeEnv = await askQuestion('Environment (development/production) [development]: ') || 'development';

    // News Configuration
    log('\n📰 News Configuration', 'magenta');
    const cacheDuration = await askQuestion('Cache duration in minutes [5]: ') || '5';
    const fetchInterval = await askQuestion('Fetch interval in minutes [10]: ') || '10';
    const maxArticles = await askQuestion('Max articles per source [10]: ') || '10';

    // Feature Flags
    log('\n🎛️  Feature Configuration', 'magenta');
    const enableAI = await askQuestion('Enable AI summaries? (Y/n): ') || 'Y';
    const enableRealtime = await askQuestion('Enable real-time features? (Y/n): ') || 'Y';
    const enableAuth = await askQuestion('Enable user authentication? (y/N): ') || 'N';

    // Generate .env content
    const envContent = `# Code Muse Board - Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# ===========================================
# OpenAI Configuration
# ===========================================
OPENAI_API_KEY=${openaiKey || 'your-openai-api-key-here'}
OPENAI_MODEL=${openaiModel}
OPENAI_MAX_TOKENS=${maxTokens}
OPENAI_TEMPERATURE=0.7

# ===========================================
# Server Configuration
# ===========================================
PORT=${port}
NODE_ENV=${nodeEnv}
HOST=localhost

# ===========================================
# News Configuration
# ===========================================
NEWS_CACHE_DURATION=${parseInt(cacheDuration) * 60 * 1000}
NEWS_FETCH_INTERVAL=${parseInt(fetchInterval) * 60 * 1000}
NEWS_REALTIME_INTERVAL=30000
NEWS_MAX_ARTICLES_PER_SOURCE=${maxArticles}
NEWS_DUPLICATE_THRESHOLD=0.8

# ===========================================
# Feature Flags
# ===========================================
ENABLE_AI_SUMMARIES=${enableAI.toLowerCase() === 'y' || enableAI.toLowerCase() === 'yes'}
ENABLE_REALTIME_FEATURES=${enableRealtime.toLowerCase() === 'y' || enableRealtime.toLowerCase() === 'yes'}
ENABLE_USER_AUTHENTICATION=${enableAuth.toLowerCase() === 'y' || enableAuth.toLowerCase() === 'yes'}
ENABLE_ANALYTICS=true
ENABLE_DARK_MODE=true
ENABLE_PWA=true

# ===========================================
# Security Configuration
# ===========================================
JWT_SECRET=${generateRandomString(32)}
SESSION_SECRET=${generateRandomString(32)}
BCRYPT_ROUNDS=12

# ===========================================
# CORS Configuration
# ===========================================
CORS_ORIGIN=http://localhost:8080
CORS_CREDENTIALS=true

# ===========================================
# Logging Configuration
# ===========================================
LOG_LEVEL=info
DEBUG=false
`;

    // Write .env file
    fs.writeFileSync(envPath, envContent);
    log('\n✅ .env file created successfully!', 'green');

    // Create data directory
    const dataDir = path.join(__dirname, 'data');
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
      log('✅ Data directory created', 'green');
    }

    // Create logs directory
    const logsDir = path.join(__dirname, 'logs');
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
      log('✅ Logs directory created', 'green');
    }

    // Display next steps
    log('\n🎉 Setup Complete!', 'green');
    log('==================\n', 'green');
    
    log('Next steps:', 'blue');
    log('1. Install dependencies: npm install', 'yellow');
    log('2. Start the application: npm run dev:full', 'yellow');
    log('3. Open your browser: http://localhost:8080', 'yellow');
    log('4. View API docs: http://localhost:3001/api-docs', 'yellow');
    
    if (!openaiKey) {
      log('\n⚠️  Note: AI summaries are disabled without OpenAI API key', 'yellow');
      log('   You can add your API key to .env file later', 'yellow');
    }

    log('\n📚 Documentation:', 'blue');
    log('   - Configuration Guide: CONFIGURATION_GUIDE.md', 'yellow');
    log('   - Quick Reference: QUICK_CONFIG_REFERENCE.md', 'yellow');
    log('   - API Documentation: API_DOCUMENTATION.md', 'yellow');

  } catch (error) {
    log(`\n❌ Setup failed: ${error.message}`, 'red');
    process.exit(1);
  } finally {
    rl.close();
  }
}

// Generate random string for secrets
function generateRandomString(length) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// Run setup
setup().catch(console.error);
